name: Setup

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version'
        type: string
        required: true
      extensions:
        description: 'PHP extensions'
        type: string
        required: true

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      key: php_${{ inputs.php-version }}_cache_v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache environment
        id: ext_cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.ext_cache.outputs.dir }}
          key: ${{ steps.ext_cache.outputs.key }}
          restore-keys: ${{ steps.ext_cache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ env.key }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ env.key }}-${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate
