name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2 ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Include Setup Workflow
        uses: ./.github/workflows/setup.yml
        with:
          php-version: ${{ matrix.php }}
          extensions: dom,curl,libxml,mbstring,zip,pcntl,pdo,sqlite,pdo_sqlite

      - name: Execute tests
        run: vendor/bin/phpunit
